### ISSUE TITLE
CAN YOU HELP ME IN MY HYBRID CLASSIFICATION METHOD FOR HEART DEASESE PREDICTION?

### ISSUE THREAD

**Issue by unknown687** [chayandatta/Heart_disease_prediction#4]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by freelancing-account** [comment]
Hi @ravichoubey5 , check your git account for collaborations. we can meet there.

**Comment by freelancing-account** [comment]
@ravichoubey5 , can you accept my invitation
